### ISSUE TITLE
Investigate netplan configuration issues in Ubuntu2404

### ISSUE THREAD

**Issue by aleixrm** [OpenNebula/one-apps#242]
We are having connectivity problems when we launch Ubuntu2404 VMs with Netplan as network configuration manager. Apparently, netplan creates a config file that conflicts with the one created by OpenNebula contextualization:
```
root@dynamo-1052:~# cat /etc/netplan/90-NM-8e2d6111-9e93-4dde-b809-0b43e5382053.yaml
network:
  version: 2
  ethernets:
    NM-8e2d6111-9e93-4dde-b809-0b43e5382053:
      renderer: NetworkManager
      match:
        name: "eth0"
      dhcp4: true
      dhcp6: true
      ipv6-address-generation: "eui64"
      wakeonlan: true
      networkmanager:
        uuid: "8e2d6111-9e93-4dde-b809-0b43e5382053"
        name: "eth0"
        passthrough:
          connection.timestamp: "1744811515"
          ethernet._: ""
          proxy._: ""
```

deleting this file or setting the `NETCFG_TYPE` context parameter to `networkd` solves the problem.
