### ISSUE TITLE
one-context fails to config ip default route with netplan on Debian 12

### ISSUE THREAD

**Issue by leandroembu** [OpenNebula/one-apps#74]
I'm using two NICs (private and public) in two VMs.
In Debian 11, with /etc/network/interfaces, everything works fine with one-context and I get my IP route via public NIC/Network.
In Debian 12 I get a lot of issues:

- Using the two NICs - Error: Conflicting default route declarations for IPv4 (table: main, metric: 0), first declared in eth1 but also in eth0.
    - Despite the conflict, the default route comes via private NIC and I can't even ping my public IP. 
- Using only the public NIC: no ip route at all, no errors reported in syslog, and I can't ping my public IP.

I am using the same two virtual networks for both VMs, but the one with Debian 11 and /etc/network/interfaces has no issues. I guess its not a Netplan's problem.

Here is the /etc/netplan/50-one-context.yaml generated by one-context:

```yaml
# Generated by one-context
network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      addresses:
        - <public-ip>/32
      routes:
        - to: "0.0.0.0/0"
          via: <public-gateway>
          metric: 0
    eth1:
      addresses:
        - 10.10.114.160/16
      routes:
        - to: "0.0.0.0/0"
          via: 10.10.114.1
          metric: 0
```

Here is the default route after the “Error: Conflicting default route declarations for IPv4 (table: main, metric: 0), first declared in eth1 but also in eth0”:

```
default via 10.10.114.1 dev eth1 proto static 
10.10.0.0/16 dev eth1 proto kernel scope link src 10.10.114.160
```

I can’t get the ip route from my public NIC, even if I start the VM only with public NIC.
